=== mikepatrick/zendserver-sdk-java/org.zend.sdk/resources/schemas/repository.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
           xmlns="http://zend-sdk.googlecode.com/site-descriptor/1.0"
           targetNamespace="http://zend-sdk.googlecode.com/site-descriptor/1.0"
           elementFormDefault="qualified">
	<xs:element name="site">
		<xs:annotation>
			<xs:documentation>Site Descriptor</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="description" minOccurs="0" maxOccurs="1" />
				<xs:element name="artifact" minOccurs="1" maxOccurs="1" />
				<xs:element name="category-def" minOccurs="0" maxOccurs="1" />
				<xs:element ref="provider-def" minOccurs="0" maxOccurs="1" />
			</xs:sequence>

			<xs:attribute name="version" type="xs:string" use="required">
				<xs:annotation>
					<xs:documentation>Site descriptor format version</xs:documentation>
				</xs:annotation>
			</xs:attribute>

		</xs:complexType>
	</xs:element>

	<xs:element name="artifact">
		<xs:annotation>
			<xs:documentation>Artifact declaration</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="url" minOccurs="1" maxOccurs="1" />
				<xs:element name="version" minOccurs="1" maxOccurs="1" />
				<xs:element name="size" minOccurs="0" maxOccurs="1" />
				<xs:element name="signature" minOccurs="0" maxOccurs="1" />
				<xs:element name="category" minOccurs="0" maxOccurs="1" />
				<xs:element name="provider" minOccurs="0" maxOccurs="1" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>


	<xs:element name="category-def">
		<xs:annotation>
			<xs:documentation>Category definition</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="name" minOccurs="1" maxOccurs="1" />
				<xs:element name="label" minOccurs="1" maxOccurs="1" />
				<xs:element name="description" minOccurs="0" maxOccurs="1" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="provider-def">
		<xs:annotation>
			<xs:documentation>Provider definition</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="name" minOccurs="1" maxOccurs="1" />
				<xs:element name="label" minOccurs="1" maxOccurs="1" />
				<xs:element name="icon" minOccurs="0" maxOccurs="1" />
				<xs:element name="url" minOccurs="0" maxOccurs="1" />
				<xs:element name="description" minOccurs="0" maxOccurs="1" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== mikepatrick/zendserver-sdk-java/zendserver-sdk-java/org.zend.sdk.tests/test/org/zend/sdk/test/sdklib/repository/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<s:site version="" xmlns:s="http://zend-sdk.googlecode.com/site-descriptor/1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://zend-sdk.googlecode.com/site-descriptor/1.0 repository.xsd ">
  <description>My Example Application Site</description>
  <s:artifact name="org.zend.drupal" version="6.19" url="/drupal/drupal-6.19.zpk">
    <size>1328376</size>
    <signature>67b6c6fd6d565758d2f997e7d91d320b</signature>
    <category>cms</category>
    <provider>bcquia</provider>
  </s:artifact>
  <s:category-def name="cms" label="Control Managment System" >
    <description>Description of Control Managment System</description>
  </s:category-def>
  <s:provider-def label="Bcquia" name="bcquia">
    <icon>http://my.fake//my.png</icon>
    <url>http://www.zend.com</url>
    <description>description of the application</description>
  </s:provider-def>
</s:site>
